apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-examquiz
  namespace: freelancy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-examquiz
  template:
    metadata:
      labels:
        app: mysql-examquiz
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-examquiz-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: exam_quiz_db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-examquiz-service
  namespace: freelancy
spec:
  selector:
    app: mysql-examquiz
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP