apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: freelancy
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'eureka-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eureka-service:8761']

      - job_name: 'challenge-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['challenge-service:8077']

      - job_name: 'examquiz-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['examquiz-service:8150']

      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-gateway-service:8091']