spring.application.name=smart-freelance-backend
server.port=8090

# OAuth2 Resource Server (Keycloak)
app.keycloak.issuer=${APP_KEYCLOAK_ISSUER:http://localhost:8081/realms/smart-platform}
app.keycloak.jwk-set-uri=${APP_KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/smart-platform/protocol/openid-connect/certs}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_freelance?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Keycloak Admin
keycloak.admin.base-url=${KEYCLOAK_ADMIN_URL:http://localhost:8081}
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.admin-realm=master
keycloak.admin.target-realm=smart-platform
keycloak.admin.client-id=angular-app
keycloak.admin.verify-email-redirect-uri=http://localhost:4200/signin

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never