spring.application.name=challenge-service
server.port=8077

# DataSource — from K8s env variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka — from K8s env variable
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# GitHub & Sonar
github.token=${GITHUB_TOKEN:}
sonar.token=${SONAR_TOKEN:}

# Keycloak
keycloak.admin.url=${KEYCLOAK_ADMIN_URL:http://keycloak:8080}
keycloak.admin.realm=smart-platform
keycloak.admin.username=admin
keycloak.admin.password=admin

app.keycloak.issuer=${APP_KEYCLOAK_ISSUER}
app.keycloak.jwk-set-uri=${APP_KEYCLOAK_JWK_SET_URI}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true