apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-analysis-config
  namespace: freelancy
data:
  # Exemple de configuration (override en production)
  GROQ_API_KEY: ""
  FRONTEND_URL: "http://localhost:4200"
