apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-config
  namespace: skill
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/skill_db?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: skill_user
  SPRING_DATASOURCE_PASSWORD: skill_pass
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka