apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
  namespace: matching
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-module
  template:
    metadata:
      labels:
        app: matching-module
    spec:
      containers:
        - name: matching-module
          image: arijachach/matching-module:latest
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: matching-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 15