apiVersion: v1
kind: Secret
metadata:
  name: contrat-secret
  namespace: freelancy          # ✅ Namespace correct
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ""   # Set database password (override in real deployment)
