apiVersion: v1
kind: Service
metadata:
  name: contrat-service
  namespace: freelancy
spec:
  selector:
    app: contrat
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
      nodePort: 30097
  type: NodePort