apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: freelancy
  labels:
    app: blog-service
spec:
  type: NodePort
  selector:
    app: blog-service
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
