apiVersion: v1
kind: ConfigMap
metadata:
  name: planning-config
  namespace: freelancy
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-planning:3306/planningdb
  SPRING_DATASOURCE_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SERVER_PORT: "8089"
