apiVersion: v1
kind: ConfigMap
metadata:
  name: planning-config
  namespace: freelancy
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-planning:3306/planningdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpass"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL8Dialect"
  SERVER_PORT: "8089"
