apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-planning
  namespace: freelancy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-planning
  template:
    metadata:
      labels:
        app: mysql-planning
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planning-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: planningdb
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-planning
  namespace: freelancy
spec:
  selector:
    app: mysql-planning
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
